### ISSUE TITLE
Please consider a more permissive license

### ISSUE THREAD

**Issue by yesudeep** [gutjuri/tries#1]
Could you please consider a more permissive license?

**Comment by gutjuri** [comment]
Do you have any suggestion?
I only want to support Free Software. Since other popular licenses such as MIT, Apache 2.0 or GNU LGPL permit usage in proprietary software, i'll not license under those.

**Comment by yesudeep** [comment]
Well, even open source software that is more permissive cannot use the library in that case. Closing the request in that case.
